packages:
  github.com/cecobask/instagram-insights/pkg/filesystem:
    interfaces:
      Fs:
        config:
          dir: "{{.InterfaceDir}}"
          filename: "{{.PackageName}}_mock.go"
          inpackage: true
          outpkg: "{{.PackageName}}"
